import { useState, useMemo } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Copy, ExternalLink, Lock, Search, FileText } from "lucide-react";

// ── Static manifest import ────────────────────────────────────────────────────
// The manifest is loaded from the canonical JSON files generated by generateRepoManifest.js.
// In production these would be fetched from raw.githubusercontent.com.
// For the admin panel we import them directly since they're in-repo.

import MANIFEST from "@/components/governance/REPO_FILE_MANIFEST.json";
import PRIORITY from "@/components/governance/PRIORITY_REPO_FILES.json";

// ── Constants ─────────────────────────────────────────────────────────────────

const CATEGORY_COLORS = {
  governance:  "bg-purple-100 text-purple-800",
  audits:      "bg-amber-100 text-amber-800",
  projects:    "bg-blue-100 text-blue-800",
  pages:       "bg-sky-100 text-sky-800",
  components:  "bg-teal-100 text-teal-800",
  admin:       "bg-slate-100 text-slate-700",
  utils:       "bg-green-100 text-green-800",
  config:      "bg-orange-100 text-orange-800",
  docs:        "bg-pink-100 text-pink-800",
  assets:      "bg-gray-100 text-gray-700",
  other:       "bg-gray-100 text-gray-500",
};

const PRIORITY_COLORS = {
  critical: "bg-red-100 text-red-800",
  high:     "bg-amber-100 text-amber-800",
  normal:   "bg-slate-100 text-slate-600",
};

// ── Sub-components ────────────────────────────────────────────────────────────

function CopyButton({ value, label }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(value).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };

  return (
    <button
      onClick={handleCopy}
      title={`Copy ${label}`}
      className="inline-flex items-center gap-1 text-xs text-slate-400 hover:text-slate-700 transition-colors px-1.5 py-0.5 rounded hover:bg-slate-100"
    >
      <Copy className="w-3 h-3" />
      {copied ? "Copied!" : label}
    </button>
  );
}

function OpenButton({ url, label }) {
  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      title={`Open ${label}`}
      className="inline-flex items-center gap-1 text-xs text-slate-400 hover:text-slate-700 transition-colors px-1.5 py-0.5 rounded hover:bg-slate-100"
    >
      <ExternalLink className="w-3 h-3" />
      {label}
    </a>
  );
}

function FileRow({ file }) {
  return (
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 py-2 border-b border-slate-100 last:border-0">
      <div className="flex items-center gap-2 min-w-0">
        {file.locked && (
          <Lock className="w-3 h-3 shrink-0 text-red-500" title="Locked file — do not modify" />
        )}
        <span className="text-sm font-mono text-slate-700 truncate" title={file.path}>
          {file.path}
        </span>
        <Badge className={`${CATEGORY_COLORS[file.category] || CATEGORY_COLORS.other} text-xs shrink-0`}>
          {file.category}
        </Badge>
      </div>
      <div className="flex items-center gap-1 shrink-0">
        <CopyButton value={file.rawUrl} label="raw" />
        <CopyButton value={file.githubUrl} label="gh" />
        <OpenButton url={file.rawUrl} label="raw" />
        <OpenButton url={file.githubUrl} label="gh" />
      </div>
    </div>
  );
}

function PriorityRow({ file }) {
  return (
    <div className="py-2.5 border-b border-slate-100 last:border-0 space-y-1">
      <div className="flex flex-wrap items-center gap-2">
        {file.lockedFile && <Lock className="w-3 h-3 text-red-500 shrink-0" />}
        <span className="text-sm font-semibold text-slate-800">{file.label}</span>
        <Badge className={`${PRIORITY_COLORS[file.priority]} text-xs`}>{file.priority}</Badge>
        {!file.exists && <Badge className="bg-red-100 text-red-700 text-xs">missing</Badge>}
      </div>
      <p className="text-xs text-slate-500">{file.whyItMatters}</p>
      <p className="text-xs font-mono text-slate-400 truncate">{file.path}</p>
      <div className="flex gap-1">
        <CopyButton value={file.rawUrl} label="raw URL" />
        <CopyButton value={file.githubUrl} label="GitHub URL" />
        <OpenButton url={file.rawUrl} label="open raw" />
        <OpenButton url={file.githubUrl} label="open GitHub" />
      </div>
    </div>
  );
}

// ── Main panel ────────────────────────────────────────────────────────────────

export default function RepoRawAccessPanel() {
  const [query, setQuery] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [folderFilter, setFolderFilter] = useState("all");
  const [tab, setTab] = useState("priority"); // "priority" | "all"

  const allFiles = MANIFEST?.files ?? [];
  const priorityFiles = PRIORITY?.files ?? [];

  // Derive filter options
  const categories = useMemo(() => {
    const cats = new Set(allFiles.map((f) => f.category));
    return ["all", ...Array.from(cats).sort()];
  }, [allFiles]);

  const folders = useMemo(() => {
    const fols = new Set(allFiles.map((f) => f.folder));
    return ["all", ...Array.from(fols).sort()];
  }, [allFiles]);

  const filteredFiles = useMemo(() => {
    return allFiles.filter((f) => {
      const q = query.toLowerCase();
      const matchesQuery = !q || f.path.toLowerCase().includes(q) || f.fileName.toLowerCase().includes(q);
      const matchesCat = categoryFilter === "all" || f.category === categoryFilter;
      const matchesFolder = folderFilter === "all" || f.folder === folderFilter;
      return matchesQuery && matchesCat && matchesFolder;
    });
  }, [allFiles, query, categoryFilter, folderFilter]);

  if (!MANIFEST || !MANIFEST.files) {
    return (
      <Card>
        <CardContent className="p-8 text-center space-y-2">
          <FileText className="w-8 h-8 text-slate-300 mx-auto" />
          <p className="text-slate-500 font-medium">Manifest not found</p>
          <p className="text-xs text-slate-400">
            Run <code className="bg-slate-100 px-1 rounded">node tools/generateRepoManifest.js</code> to generate the manifest.
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="pb-3">
          <div className="flex flex-wrap items-start justify-between gap-2">
            <div>
              <CardTitle className="text-base text-slate-800">Repository Raw Access</CardTitle>
              <p className="text-xs text-slate-400 mt-0.5">
                {allFiles.length} files indexed · Generated {MANIFEST._meta?.generatedAt}
              </p>
            </div>
            <a
              href="https://github.com/Luckywolf82/governancehub"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-slate-500 hover:text-slate-800 flex items-center gap-1"
            >
              <ExternalLink className="w-3 h-3" /> GitHub
            </a>
          </div>

          {/* Tabs */}
          <div className="flex gap-1 mt-3 border-b border-slate-200">
            {[
              { key: "priority", label: `Priority (${priorityFiles.length})` },
              { key: "all", label: `All Files (${allFiles.length})` },
            ].map(({ key, label }) => (
              <button
                key={key}
                onClick={() => setTab(key)}
                className={`px-3 py-1.5 text-xs font-medium border-b-2 transition-colors ${
                  tab === key
                    ? "border-slate-800 text-slate-900"
                    : "border-transparent text-slate-500 hover:text-slate-700"
                }`}
              >
                {label}
              </button>
            ))}
          </div>
        </CardHeader>

        <CardContent className="pt-0">
          {tab === "priority" ? (
            <div>
              {priorityFiles.length === 0 ? (
                <p className="text-sm text-slate-400 text-center py-6">No priority files found.</p>
              ) : (
                priorityFiles.map((f) => <PriorityRow key={f.path} file={f} />)
              )}
            </div>
          ) : (
            <div className="space-y-3">
              {/* Filters */}
              <div className="flex flex-wrap gap-2">
                <div className="relative flex-1 min-w-48">
                  <Search className="absolute left-2.5 top-2 w-3.5 h-3.5 text-slate-400" />
                  <Input
                    placeholder="Search by path or filename…"
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    className="pl-7 h-8 text-xs"
                  />
                </div>
                <select
                  value={categoryFilter}
                  onChange={(e) => setCategoryFilter(e.target.value)}
                  className="h-8 text-xs border border-slate-200 rounded-md px-2 text-slate-700 bg-white"
                >
                  {categories.map((c) => (
                    <option key={c} value={c}>{c === "all" ? "All categories" : c}</option>
                  ))}
                </select>
                <select
                  value={folderFilter}
                  onChange={(e) => setFolderFilter(e.target.value)}
                  className="h-8 text-xs border border-slate-200 rounded-md px-2 text-slate-700 bg-white max-w-48 truncate"
                >
                  {folders.map((f) => (
                    <option key={f} value={f}>{f === "all" ? "All folders" : f}</option>
                  ))}
                </select>
              </div>

              {filteredFiles.length === 0 ? (
                <p className="text-sm text-slate-400 text-center py-6">No files match your filters.</p>
              ) : (
                <div>
                  <p className="text-xs text-slate-400 mb-2">{filteredFiles.length} file{filteredFiles.length !== 1 ? "s" : ""}</p>
                  {filteredFiles.map((f) => <FileRow key={f.path} file={f} />)}
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}