// PromptProfileRegistry — governance schema/data artifact
// gov-005 Phase 1 — created 2026-03-16
// Project: GovernanceHub (projectId: governancehub, projectSlug: governancehub)
//
// This file is a pure schema/data artifact.
// No UI components, no dispatch logic, no approval workflow implementation.
// Registry must be treated as a governance artifact subject to locked-file policy
// once formally adopted (see governanceConstraints below).

// ── Schema ─────────────────────────────────────────────────────────────────────
// Every entry in the profiles array must include all requiredProfileFields.
// A profile with approvalStatus !== 'approved' must not be used to trigger dispatch.

export const requiredProfileFields = [
  "id",
  "name",
  "version",
  "targetAudience",
  "intentDescription",
  "templateBody",
  "allowedVariables",
  "createdBy",
  "createdAt",
  "approvalStatus",
  "approvedBy",
  "approvedAt",
];

// ── Governance constraints ─────────────────────────────────────────────────────

export const governanceConstraints = [
  "Profiles must be stored in this versioned, auditable registry — not inline in UI components.",
  "Profile content changes must increment the version field.",
  "A profile with approvalStatus !== 'approved' must not be dispatchable.",
  "Profile registry must be treated as a governance artifact subject to locked-file policy once formally adopted.",
];

// ── Allowed dispatch targets ────────────────────────────────────────────────────
// Targets correspond to staged-rollout stages defined in gov-005.
// Stage progression must be sequential — internal → pilot → full.
// Each stage transition requires a new dispatch log entry and a new approval record.

export const allowedTargets = [
  {
    stage: 1,
    label: "internal",
    description: "Dispatch to internal operator accounts only (self-test)",
    maxTargetCount: 5,
    approvalRequired: "operator-self-approve",
  },
  {
    stage: 2,
    label: "pilot",
    description: "Dispatch to a named pilot group (defined in profile)",
    maxTargetCount: 50,
    approvalRequired: "second-operator-approve",
  },
  {
    stage: 3,
    label: "full",
    description: "Dispatch to all eligible targets",
    maxTargetCount: null,
    approvalRequired: "governance-review",
  },
];

// ── Approval status vocabulary ─────────────────────────────────────────────────

export const approvalStatusVocabulary = [
  "draft",
  "pending-review",
  "approved",
  "deprecated",
];

// ── Profile registry ───────────────────────────────────────────────────────────
// Initial registry. All profiles are in 'draft' status until reviewed and approved
// through the approval gate defined in gov-005 (PromptApprovalGate — to be created).

export const PROMPT_PROFILE_REGISTRY = {
  meta: {
    registryId: "prompt-profile-registry",
    version: "1.0.0",
    governedBy: "gov-005",
    projectId: "governancehub",
    projectSlug: "governancehub",
    createdAt: "2026-03-16",
    description:
      "Versioned registry of operator prompt profiles for GovernanceHub. " +
      "Each profile defines the intent, target audience, content structure, and governance " +
      "metadata for a class of operator-generated prompts. Profiles allow operators to tailor " +
      "prompt content within pre-approved boundaries without bypassing governance review.",
  },

  profiles: [
    {
      id: "profile-001",
      name: "Governance Status Update",
      version: "1.0.0",
      targetAudience: "internal",
      intentDescription:
        "Notify internal operators of the current governance phase and next safe step.",
      templateBody:
        "GovernanceHub governance status update — {{date}}\n\n" +
        "Project: {{projectName}}\n" +
        "Current phase: {{currentPhase}}\n" +
        "Last verified step: {{lastVerifiedStep}}\n" +
        "Next safe step: {{nextSafeStep}}\n\n" +
        "This message was generated by GovernanceHub and dispatched after operator review and approval.",
      allowedVariables: [
        "date",
        "projectName",
        "currentPhase",
        "lastVerifiedStep",
        "nextSafeStep",
      ],
      createdBy: "governance-system",
      createdAt: "2026-03-16",
      approvalStatus: "draft",
      approvedBy: null,
      approvedAt: null,
    },
    {
      id: "profile-002",
      name: "Audit Completion Notice",
      version: "1.0.0",
      targetAudience: "internal",
      intentDescription:
        "Notify internal operators that a governance audit has been completed and verified.",
      templateBody:
        "Governance audit completed — {{date}}\n\n" +
        "Audit ID: {{auditId}}\n" +
        "Title: {{auditTitle}}\n" +
        "Status: {{auditStatus}}\n" +
        "Findings summary: {{findingsSummary}}\n\n" +
        "This message was generated by GovernanceHub and dispatched after operator review and approval.",
      allowedVariables: [
        "date",
        "auditId",
        "auditTitle",
        "auditStatus",
        "findingsSummary",
      ],
      createdBy: "governance-system",
      createdAt: "2026-03-16",
      approvalStatus: "draft",
      approvedBy: null,
      approvedAt: null,
    },
  ],
};
